version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - FRONTEND_URL=https://spreadify-ai.vercel.app
      - PUBLIC_URL=http://localhost:8000
      - DATABASE_URL=sqlite:////app/data/app.db
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data  # For SQLite database persistence
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]
