version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - FRONTEND_URL=https://spreadify-ai.vercel.app
      - PUBLIC_URL=http://localhost:8000
      - DATABASE_URL=sqlite:////app/data/app.db
      - JWT_SECRET=${JWT_SECRET:-default_jwt_secret}
      - PYTHONUNBUFFERED=1
      - DOCKER_ENV=1
      - LOG_LEVEL=debug
    volumes:
      - sqlite_data:/app/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

volumes:
  sqlite_data:
    driver: local
