app = "spreadify-api"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  FRONTEND_URL = "https://stream-live-app-xabl732t.devinapps.com"
  PUBLIC_URL = "https://spreadify-api.fly.dev"
  OAUTH_REDIRECT_URL = "https://spreadify-api.fly.dev/auth/callback"
  CORS_ORIGINS = '["https://stream-live-app-xabl732t.devinapps.com", "http://localhost:5173", "http://localhost:3000"]'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
