[build]
builder = "DOCKERFILE"
buildCommand = "docker build -t spreadify-backend ."

[deploy]
startCommand = "docker run -p $PORT:8000 -e FRONTEND_URL=$FRONTEND_URL -e PUBLIC_URL=$PUBLIC_URL -e OAUTH_REDIRECT_URL=$OAUTH_REDIRECT_URL -e CORS_ORIGINS=$CORS_ORIGINS -e GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID -e GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET -e JWT_SECRET=$JWT_SECRET -e STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY -e DATABASE_URL=$DATABASE_URL spreadify-backend"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = "8000"
FRONTEND_URL = "https://spreadify-ai.vercel.app"
PUBLIC_URL = "https://spreadify-api.railway.app"
OAUTH_REDIRECT_URL = "https://spreadify-api.railway.app/auth/callback"
CORS_ORIGINS = '["https://spreadify-ai.vercel.app", "http://localhost:5173", "http://localhost:3000"]'
DATABASE_URL = "${{Postgres.DATABASE_URL}}"

[[services]]
name = "spreadify-backend"
internal_port = 8000
protocol = "http"
healthcheck = {
  path = "/healthz",
  interval = "30s",
  timeout = "10s",
  retries = 3
}

[[services.ports]]
handlers = ["http"]
port = "80"
