[build]
builder = "DOCKERFILE"
buildCommand = "docker build -t spreadify-backend ."

[deploy]
startCommand = "docker run -p $PORT:8000 spreadify-backend"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = "8000"
FRONTEND_URL = "https://spreadify-ai.vercel.app"
PUBLIC_URL = "https://spreadify-api.railway.app"
OAUTH_REDIRECT_URL = "https://spreadify-api.railway.app/auth/callback"
CORS_ORIGINS = '["https://spreadify-ai.vercel.app", "http://localhost:5173", "http://localhost:3000"]'
DATABASE_URL = "${{Postgres.DATABASE_URL}}"

[[services]]
name = "spreadify-backend"
internal_port = 8000
protocol = "http"
healthcheck = {
  path = "/healthz",
  interval = "30s",
  timeout = "10s",
  retries = 3
}

[[services.ports]]
handlers = ["http"]
port = "80"
