[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "poetry run uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.12"
PORT = "8000"
FRONTEND_URL = "https://spreadify-ai.vercel.app"
PUBLIC_URL = "https://spreadify-api.railway.app"
OAUTH_REDIRECT_URL = "https://spreadify-api.railway.app/auth/callback"
CORS_ORIGINS = '["https://spreadify-ai.vercel.app", "http://localhost:5173", "http://localhost:3000"]'
DATABASE_URL = "${{Postgres.DATABASE_URL}}"

# Note: Sensitive environment variables should be set through Railway's dashboard:
# - GOOGLE_CLIENT_ID
# - GOOGLE_CLIENT_SECRET
# - JWT_SECRET
# - STRIPE_SECRET_KEY

[[services]]
name = "spreadify-backend"
internal_port = 8000
protocol = "http"
healthcheck = {
  path = "/healthz",
  interval = "30s",
  timeout = "10s",
  retries = 3
}

[[services.ports]]
handlers = ["http"]
port = "80"
