[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/healthz"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.12"

[[services]]
name = "spreadify-backend"
internal_port = 8080
protocol = "http"

[[services.ports]]
handlers = ["http"]
port = "80"
