services:
  - type: web
    name: spreadify-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: starter
    envVars:
      - key: PORT
        value: 8000
      - key: FRONTEND_URL
        value: https://spreadify-ai.vercel.app
      - key: PUBLIC_URL
        value: https://spreadify-api.onrender.com
    healthCheckPath: /healthz
    buildCommand: docker build -t spreadify-backend .
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT --workers 4
    autoDeploy: true
