name: Deploy to Railway

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
      
      - name: Login to Railway
        run: railway login --token ${{ secrets.RAILWAY_TOKEN }}
      
      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          cd backend
          railway up --service spreadify-backend --detach
      
      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to complete..."
          sleep 30
          curl -f https://spreadify-api.railway.app/healthz || exit 1
